import 'package:json_annotation/json_annotation.dart';

// This file will be generated by build_runner
part 'kenyan_id_data.g.dart';

/// Represents the extracted data from a Kenyan National ID.
@JsonSerializable(fieldRename: FieldRename.snake)
class KenyanIdData {
  /// The unique 7 or 8 digit ID number.
  final String idNumber;

  /// The full name of the citizen.
  final String fullName;

  /// The date of birth extracted from the document.
  final String dateOfBirth;

  /// Creates a new immutable [KenyanIdData] instance.
  const KenyanIdData({
    required this.idNumber,
    required this.fullName,
    required this.dateOfBirth,
  });

  /// Creates a [KenyanIdData] from a JSON map.
  factory KenyanIdData.fromJson(Map<String, dynamic> json) => 
      _$KenyanIdDataFromJson(json);

  /// Converts this [KenyanIdData] to a JSON map.
  Map<String, dynamic> toJson() => _$KenyanIdDataToJson(this);
}